Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcE_Learning.Data;
using MvcE_Learning.Models;

namespace MvcE_Learning.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CourseDbContext _context;
        private readonly InstructorsDbContext _instructorContext;
        private readonly TeachDbContext _teachContext;
        private readonly ContentDbContext _contentContext;

        public CoursesController(CourseDbContext context, InstructorsDbContext instructorContext, TeachDbContext teachContext, ContentDbContext contentContext)
        {
            _context = context;
            _instructorContext = instructorContext;
            _teachContext = teachContext;
            _contentContext = contentContext;
        }

        // GET: Courses
        public async Task<IActionResult> Index(string courseFields, string searchString)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'MvcE_Learning.Course'  is null.");
            }

            
            IQueryable<string> fieldsQuery = from m in _context.Course
                                            orderby m.Fields
                                            select m.Fields;
            var courses = from c in _context.Course
                         select c;

            if (!string.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(s => s.Name!.ToUpper().Contains(searchString.ToUpper()));
            }

            if (!string.IsNullOrEmpty(courseFields))
            {
                courses = courses.Where(x => x.Fields == courseFields);
            }

            var courseFieldVM = new CourseViewModel
            {
                Fields = new SelectList(await fieldsQuery.Distinct().ToListAsync()),
                Course = await courses.ToListAsync()
            };

            return View(courseFieldVM);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courses = from c in _context.Course
                          select c;

            courses = courses.Where(c => c.CourseId == id);

            var course =  courses.FirstOrDefault();

            var content = from c in _contentContext.Content
                          where c.CourseId == id
                          select c;

            ICollection<Content> contents = content.ToList();

            CourseContentViewModel courseContentViewModel = new CourseContentViewModel();

            courseContentViewModel.Course = course;
            courseContentViewModel.Contents = contents;


            if (course == null)
            {
                return NotFound();
            }

            return View(courseContentViewModel);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("courseId,Name,Description,Duration,Difficulty,Fields,Rating")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                var courses = from c in _context.Course
                              select c;

                courses = courses.Where(i => i.Name == course.Name);
                courses = courses.Where(i => i.Description == course.Description);
                var courseId = courses.FirstOrDefault().CourseId;
                Teach teach = new Teach();
                teach.CourseId = courseId;
                teach.InstructorId = Int32.Parse(Request.Cookies["Id"]);
                _teachContext.Add(teach);

                await _teachContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("courseId,Name,Description,Duration,Difficulty,Fields,Rating")] Course course)
        {
            if (id != course.CourseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.CourseId == id);
        }
    }
}

Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcE_Learning.Data;
using MvcE_Learning.Models;

namespace MvcE_Learning.Controllers
{
    public class StudentsController : Controller
    {
        private readonly StudentsDbContext _context;
        private readonly CourseDbContext _courseContext;
        private readonly EnrollDbContext _enrollContext;
        private readonly RatingDbContext _ratingContext;

        public StudentsController(StudentsDbContext context, CourseDbContext courseDbContext, EnrollDbContext enrollDbContext , RatingDbContext ratingDbContext)
        {
            _context = context;
            _courseContext = courseDbContext;
            _enrollContext = enrollDbContext;
            _ratingContext = ratingDbContext;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());
        }

        public IActionResult Login()
        {
            return View();
        }

        public async Task<IActionResult> Home()
        {
            var userId = Int32.Parse(Request.Cookies["Id"]);
            var courses = from c in _courseContext.Course
                          select c;
            var enroll = from t in _enrollContext.Enroll
                          select t;

            var ratings = from t in _ratingContext.Rating
                          select t;
            ratings = ratings.Where(r => r.StudentId == userId);
            enroll = enroll.Where(t => t.StudentId == userId);
            Console.WriteLine("Hello Hello");
            int[] courseIdList = new int[enroll.Count()];
            int counter = 0;
            foreach (Enroll t in enroll)
            {
                courseIdList[counter] = t.CourseId;
                counter++;
            }

            courses = courses.Where(c => courseIdList.Contains(c.CourseId));
            ratings = ratings.Where(r => courseIdList.Contains(r.CourseId));
            int[] ratingsListCourseIds = new int[ratings.Count()];
            counter = 0;
            Console.WriteLine(ratings);
            foreach(Rating r in ratings)
            {
                ratingsListCourseIds[counter] = r.CourseId;
                counter++;
            }
            Console.WriteLine("Rating size is: " + ratings.Count());
 
            IEnumerable<CourseRatingViewModel> crvm = Enumerable.Empty<CourseRatingViewModel>();
            foreach(Course course in courses)
            {
                Console.WriteLine("Inside Loop");
                CourseRatingViewModel crvmEntity = new CourseRatingViewModel();
                crvmEntity.course = course;
                int courseId = crvmEntity.course.CourseId;
                if(ratingsListCourseIds.Contains(course.CourseId))
                {
                    crvmEntity.rated = true;
                    var Erating = ratings.Where(r => r.CourseId == courseId);
                    Erating = Erating.Where(r => r.StudentId == userId);
                    crvmEntity.rating = Erating.First().rating;
                    crvmEntity.ratingId = Erating.First().RatingId;
                }
                else
                {
                    crvmEntity.rated = false;
                }
                crvm = crvm.Append(crvmEntity);
                Console.WriteLine("Entity has details: " + crvmEntity.course.CourseId + " " + crvmEntity.rating);
            }
            Console.WriteLine("Courses size is: " + courses.Count());
            Console.WriteLine("CRVM Size is: " + crvm.Count());
            return View(crvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Email,Password")] Student student)
        {
            if (string.IsNullOrEmpty(student.Email) && string.IsNullOrEmpty(student.Password))
            {
                return BadRequest();
            }
            var studentSearch = from i in _context.Students
                                   select i;
            studentSearch = studentSearch.Where(s => s.Email == student.Email);
            studentSearch = studentSearch.Where(s => s.Password == student.Password);

            Student returnStudent = studentSearch.FirstOrDefault();

            if (returnStudent != null)
            {
                Console.WriteLine(returnStudent.Email);
                HttpContext.Response.Cookies.Append("Role", "Student");
                HttpContext.Response.Cookies.Append("Name", returnStudent.Name);
                HttpContext.Response.Cookies.Append("Id", returnStudent.StudentId.ToString());
                return Redirect("/Students/Home");
            }
            else
            {
                StudentLoginSuccess studentLoginSuccess = new StudentLoginSuccess();
                studentLoginSuccess.success = false;
                //studentLoginSuccess.student = new Student();
                //studentLoginSuccess.student.Email = student.Email;
                //studentLoginSuccess.student.Password = student.Password;
                return View(studentLoginSuccess);

            }
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Enroll(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentId = Int32.Parse(Request.Cookies["Id"]);
            Enroll enrolled = new Enroll();
            enrolled.StudentId = studentId;
            enrolled.CourseId = (int) id;
            _enrollContext.Add(enrolled);
            _enrollContext.SaveChanges();
            return Redirect("/Courses");
        }

        public IActionResult LogOut()
        {
            HttpContext.Response.Cookies.Delete("Role");
            HttpContext.Response.Cookies.Delete("Registered");
            HttpContext.Response.Cookies.Delete("Name");
            return Redirect("/");
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentId,Name,Email,Password,Age,AreasOfInterest,EducationLevel")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                HttpContext.Response.Cookies.Append("Role", "Student");
                HttpContext.Response.Cookies.Append("Name", student.Name);
                HttpContext.Response.Cookies.Append("Id", student.StudentId.ToString());
                return RedirectToAction(nameof(Home));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StudentId,Name,Email,Password,Age,AreasOfInterest,EducationLevel")] Student student)
        {
            if (id != student.StudentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }

            await _context.SaveChangesAsync();

Views/Shared/_Layout.cshtml
@{
    var role = Context.Request.Cookies["Role"];  // Get the Role cookie
    var name = Context.Request.Cookies["Name"];  // Get the Name cookie
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E-Learners</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@4.1.1/animate.min.css">
    <style>
        :root {
            --primary-color: #4361ee;
            --secondary-color: #3f37c9;
            --accent-color: #4cc9f0;
            --light-color: #f8f9fa;
            --dark-color: #212529;
            --success-color: #4bb543;
            --warning-color: #ffcc00;
        }
        
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #f5f7fa;
            color: var(--dark-color);
            line-height: 1.6;
        }
        
        .navbar {
            background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
            box-shadow: 0 4px 18px rgba(0, 0, 0, 0.1);
            padding: 0.8rem 1rem;
        }
        
        .navbar-brand {
            font-weight: 700;
            font-size: 1.8rem;
            color: white !important;
            display: flex;
            align-items: center;
        }
        
        .navbar-brand span {
            color: var(--accent-color);
        }
        
        .nav-link {
            font-weight: 500;
            color: rgba(255, 255, 255, 0.85) !important;
            padding: 0.5rem 1rem !important;
            margin: 0 0.25rem;
            border-radius: 0.5rem;
            transition: all 0.3s ease;
        }
        
        .nav-link:hover {
            color: white !important;
            background-color: rgba(255, 255, 255, 0.1);
            transform: translateY(-2px);
        }
        
        .nav-link.btn {
            color: var(--primary-color) !important;
            background-color: white;
            border: none;
            font-weight: 600;
            padding: 0.5rem 1.5rem !important;
        }
        
        .nav-link.btn:hover {
            background-color: rgba(255, 255, 255, 0.9);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        }
        
        .container {
            max-width: 1200px;
        }
        
        .welcome-alert {
            border-left: 4px solid var(--success-color);
            background-color: white;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
            border-radius: 0.5rem;
            margin-bottom: 2rem;
            animation: fadeInDown 0.5s;
        }
        
        .footer {
            background: linear-gradient(135deg, var(--dark-color), #2b2d42);
            color: white;
            padding: 2rem 0;
            margin-top: 3rem;
        }
        
        .footer a {
            color: var(--accent-color);
            text-decoration: none;
            transition: all 0.3s ease;
        }
        
        .footer a:hover {
            color: white;
            text-decoration: underline;
        }
        
        .floating {
            animation: float 3s ease-in-out infinite;
        }
        

        .gradient-text {
            background: linear-gradient(45deg, var(--primary-color), var(--accent-color));
            -webkit-background-clip: text;
            background-clip: text;
            color: transparent;
        }
        

        .card {
            border: none;
            border-radius: 1rem;
            box-shadow: 0 6px 15px rgba(0, 0, 0, 0.05);
            transition: all 0.3s ease;
            overflow: hidden;
        }
        
        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 12px 20px rgba(0, 0, 0, 0.1);
        }
        

        .btn-primary {
            background-color: var(--primary-color);
            border-color: var(--primary-color);
            padding: 0.5rem 1.75rem;
            font-weight: 500;
            border-radius: 0.5rem;
        }
        
        .btn-primary:hover {
            background-color: var(--secondary-color);
            border-color: var(--secondary-color);
            transform: translateY(-2px);
            box-shadow: 0 4px 8px rgba(67, 97, 238, 0.3);
        }
        

        @@media (max-width: 768px) {
            .navbar-brand {
                font-size: 1.5rem;
            }
            
            .nav-link {
                margin: 0.25rem 0;
            }
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-graduation-cap me-2"></i>E-<span>Learners</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home me-1"></i> Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Courses" asp-action="Index">
                                <i class="fas fa-book me-1"></i> Courses
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">
                                <i class="fas fa-shield-alt me-1"></i> Privacy
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        @if (!string.IsNullOrEmpty(role) && role == "Instructor")
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Instructors" asp-action="Home">
                                    <i class="fas fa-chalkboard-teacher me-1"></i> Dashboard
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Instructors" asp-action="LogOut">
                                    <i class="fas fa-sign-out-alt me-1"></i> Sign Out
                                </a>
                            </li>
                        }
                        else if (!string.IsNullOrEmpty(role) && role == "Student")
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Students" asp-action="Home">
                                    <i class="fas fa-user-graduate me-1"></i> Dashboard
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Students" asp-action="LogOut">
                                    <i class="fas fa-sign-out-alt me-1"></i> Sign Out
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link btn btn-light" asp-area="" asp-controller="Home" asp-action="LoginPageOption">
                                    <i class="fas fa-sign-in-alt me-1"></i> Login
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container my-4">
        <main role="main">
            @if (role == "Instructor" && !string.IsNullOrEmpty(name))
            {
                <div class="alert alert-success alert-dismissible fade show welcome-alert" role="alert">
                    <i class="fas fa-chalkboard-teacher me-2"></i> Welcome back, <strong>@name</strong>! Ready to inspire your students today?
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            else if (role == "Student" && !string.IsNullOrEmpty(name))
            {
                <div class="alert alert-success alert-dismissible fade show welcome-alert" role="alert">
                    <i class="fas fa-user-graduate me-2"></i> Welcome back, <strong>@name</strong>! Keep up the great learning!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h5 class="mb-3"><i class="fas fa-graduation-cap me-2"></i> E-Learners</h5>
                    <p>Empowering your learning journey with quality education and innovative teaching methods.</p>
                    <div class="social-icons mt-3">
                        <a href="#" class="text-white me-3"><i class="fab fa-facebook-f"></i></a>
                        <a href="#" class="text-white me-3"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="text-white me-3"><i class="fab fa-instagram"></i></a>
                        <a href="#" class="text-white"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-md-3">
                    <h5 class="mb-3">Quick Links</h5>
                    <ul class="list-unstyled">
                        <li class="mb-2"><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-chevron-right me-2"></i> Home</a></li>
                        <li class="mb-2"><a asp-area="" asp-controller="Courses" asp-action="Index"><i class="fas fa-chevron-right me-2"></i> Courses</a></li>
                        <li class="mb-2"><a asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fas fa-chevron-right me-2"></i> Privacy</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h5 class="mb-3">Contact</h5>
                    <ul class="list-unstyled">
                        <li class="mb-2"><i class="fas fa-map-marker-alt me-2"></i> 123 Learning St, Edu City</li>
                        <li class="mb-2"><i class="fas fa-phone me-2"></i> (123) 456-7890</li>
                        <li class="mb-2"><i class="fas fa-envelope me-2"></i> info@elearners.com</li>
                    </ul>
                </div>
            </div>
            <hr class="my-4 bg-light">
            <div class="text-center">
                &copy; 2025 E-Learners - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
            </div>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js"></script>
    <script>

        $(document).ready(function(){
            $("a").on('click', function(event) {
                if (this.hash !== "") {
                    event.preventDefault();
                    var hash = this.hash;
                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 800, function(){
                        window.location.hash = hash;
                    });
                }
            });
            

            const animateOnScroll = function() {
                const elements = document.querySelectorAll('.card, .feature-box');
                elements.forEach(element => {
                    const elementPosition = element.getBoundingClientRect().top;
                    const windowHeight = window.innerHeight;
                    
                    if (elementPosition < windowHeight - 100) {
                        element.classList.add('animate__animated', 'animate__fadeInUp');
                    }
                });
            };
            
            window.addEventListener('scroll', animateOnScroll);
            animateOnScroll();
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>