Controllers/ContentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Scripting.Hosting;
using Microsoft.EntityFrameworkCore;
using MvcE_Learning.Data;
using MvcE_Learning.Migrations;
using MvcE_Learning.Models;

namespace MvcE_Learning.Controllers
{
    public class ContentsController : Controller
    {
        private readonly ContentDbContext _context;
        private readonly CourseDbContext _CoursesContext;

        public ContentsController(ContentDbContext context, CourseDbContext coursesContext )
        {
            _CoursesContext = coursesContext;
            _context = context;
        }

        // GET: Contents
        public async Task<IActionResult> Index()
        {

            return View(await _context.Content.ToListAsync());
        }

        // GET: Contents/Details/{id}
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _context.Content
                .FirstOrDefaultAsync(m => m.ContentId == id);
            if (content == null)
            {
                return NotFound();
            }

            return View(content);
        }

        // GET: Contents/Create
        public IActionResult Create(int courseId)
        {
            ViewData["CourseId"] = courseId;
            return View();
        }

        // POST: Contents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id, [Bind("Title,DateAdded,Type,CourseId,PdfUpload")] Content content)
        {
            content.CourseId = (int)id;



            if (ModelState.IsValid)
            {
                if (content.PdfUpload != null && content.PdfUpload.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await content.PdfUpload.CopyToAsync(memoryStream);
                        content.pdfFile = memoryStream.ToArray();
                        Console.WriteLine("Im here");
                        Console.WriteLine("HERE HERE HERE HERE :" + memoryStream.ToArray()); // Vodoo Shit
                    }
                }
                _context.Add(content);
                await _context.SaveChangesAsync();
                return Redirect("/Courses/Details/" + id);
            }
            else
            {
                var errors = string.Join(", ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage));
                Console.WriteLine($"Model state invalid: {errors}");
            }
            Console.WriteLine($"Title: {content.Title}, DateAdded: {content.DateAdded}, Type: {content.Type}, CourseId: {content.CourseId}, pdfFile: {content.pdfFile}");
            return View(content);
        }

        [HttpGet("Download/{id}")]
        public async Task<IActionResult> Download(int id)
        {
            var courses = from c in _CoursesContext.Course
                          select c;
            courses = courses.Where(c => c.CourseId == id);
            var course = courses.FirstOrDefault();


            var content = from c in _context.Content
                          where c.CourseId == id
                          select c;
            var contents = content.FirstOrDefault();


            if (content == null || contents.pdfFile == null)
            {
                return NotFound(); 
            }

            // Set the response content type for PDF
            Response.ContentType = "application/pdf";
            Response.Headers.Add("Content-Disposition", "attachment; filename=content.pdf"); 

            return File(contents.pdfFile, "application/pdf");
        }

        // GET: Contents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _context.Content.FindAsync(id);
            if (content == null)
            {
                return NotFound();
            }
            return View(content);
        }

        // POST: Contents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContentId,Title,DateAdded,Type,CourseId")] Content content)
        {
            if (id != content.ContentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(content);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContentExists(content.ContentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { courseId = content.CourseId });

            }
            return View(content);
        }

        // GET: Contents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _context.Content
                .FirstOrDefaultAsync(m => m.ContentId == id);
            if (content == null)
            {
                return NotFound();
            }

            return View(content);
        }

        // POST: Contents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var content = await _context.Content.FindAsync(id);
            if (content != null)
            {
                _context.Content.Remove(content);
            }

            await _context.SaveChangesAsync();
            return Redirect("/Instructors/Home");

        }

        private bool ContentExists(int id)
        {
            return _context.Content.Any(e => e.ContentId == id);
        }
    }
}

Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcE_Learning.Data;
using MvcE_Learning.Models;

namespace MvcE_Learning.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CourseDbContext _context;
        private readonly InstructorsDbContext _instructorContext;
        private readonly TeachDbContext _teachContext;
        private readonly ContentDbContext _contentContext;

        public CoursesController(CourseDbContext context, InstructorsDbContext instructorContext, TeachDbContext teachContext, ContentDbContext contentContext)
        {
            _context = context;
            _instructorContext = instructorContext;
            _teachContext = teachContext;
            _contentContext = contentContext;
        }

        // GET: Courses
        public async Task<IActionResult> Index(string courseFields, string searchString)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'MvcE_Learning.Course'  is null.");
            }

            
            IQueryable<string> fieldsQuery = from m in _context.Course
                                            orderby m.Fields
                                            select m.Fields;
            var courses = from c in _context.Course
                         select c;

            if (!string.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(s => s.Name!.ToUpper().Contains(searchString.ToUpper()));
            }

            if (!string.IsNullOrEmpty(courseFields))
            {
                courses = courses.Where(x => x.Fields == courseFields);
            }

            var courseFieldVM = new CourseViewModel
            {
                Fields = new SelectList(await fieldsQuery.Distinct().ToListAsync()),
                Course = await courses.ToListAsync()
            };

            return View(courseFieldVM);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courses = from c in _context.Course
                          select c;

            courses = courses.Where(c => c.CourseId == id);

            var course =  courses.FirstOrDefault();

            var content = from c in _contentContext.Content
                          where c.CourseId == id
                          select c;

            ICollection<Content> contents = content.ToList();

            CourseContentViewModel courseContentViewModel = new CourseContentViewModel();

            courseContentViewModel.Course = course;
            courseContentViewModel.Contents = contents;


            if (course == null)
            {
                return NotFound();
            }

            return View(courseContentViewModel);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("courseId,Name,Description,Duration,Difficulty,Fields,Rating")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                var courses = from c in _context.Course
                              select c;

                courses = courses.Where(i => i.Name == course.Name);
                courses = courses.Where(i => i.Description == course.Description);
                var courseId = courses.FirstOrDefault().CourseId;
                Teach teach = new Teach();
                teach.CourseId = courseId;
                teach.InstructorId = Int32.Parse(Request.Cookies["Id"]);
                _teachContext.Add(teach);

                await _teachContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("courseId,Name,Description,Duration,Difficulty,Fields,Rating")] Course course)
        {
            if (id != course.CourseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.CourseId == id);
        }
    }
}

Views/Courses/Details.cshtml
@model MvcE_Learning.Models.CourseContentViewModel

@{
    ViewData["Title"] = "Course Details";
    var role = Context.Request.Cookies["Role"];
}

<div class="container py-5">
    <div class="card shadow-lg border-0 rounded-lg overflow-hidden">
        <!-- Course Header -->
        <div class="card-header bg-primary-gradient text-white py-4">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h1 class="h3 mb-0 fw-bold">@Model.Course.Name</h1>
                    <div class="d-flex align-items-center mt-2">
                        <span class="badge bg-@GetDifficultyBadgeClass(Model.Course.Difficulty) me-2">
                            @Model.Course.Difficulty
                        </span>
                        <span class="text-white-50 me-3">
                            <i class="fas fa-clock me-1"></i> @Model.Course.Duration
                        </span>
                        <div class="text-warning">
                            @for (int i = 0; i < (int)Model.Course.Rating; i++)
                            {
                                <i class="fas fa-star"></i>
                            }
                            @if (Model.Course.Rating % 1 > 0)
                            {
                                <i class="fas fa-star-half-alt"></i>
                            }
                            <span class="text-white ms-1">@Model.Course.Rating.ToString("0.0")</span>
                        </div>
                    </div>
                </div>
                @if (role == "Instructor")
                {
                    <div>
                        <a asp-action="Edit" asp-route-id="@Model.Course.CourseId" class="btn btn-outline-light btn-sm me-2">
                            <i class="fas fa-edit me-1"></i> Edit Course
                        </a>
                        <a asp-action="Create" asp-controller="Contents" asp-route-id="@Model.Course.CourseId" class="btn btn-light btn-sm">
                            <i class="fas fa-plus me-1"></i> Add Content
                        </a>
                    </div>
                }
            </div>
        </div>

        <!-- Course Body -->
        <div class="card-body">
            <!-- Course Fields -->
            <div class="mb-4">
                @foreach (var field in Model.Course.Fields.Split(','))
                {
                    <span class="badge bg-secondary me-1">@field.Trim()</span>
                }
            </div>

            <!-- Course Description -->
            <div class="mb-5">
                <h5 class="fw-bold gradient-text mb-3">Course Description</h5>
                <p class="lead">@Model.Course.Description</p>
            </div>

            <!-- Course Content Section -->
            <div class="mb-5">
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h5 class="fw-bold gradient-text mb-0">Course Content</h5>
                    @if (role == "Instructor")
                    {
                        <a asp-controller="Instructors" asp-action="Home" class="btn btn-outline-primary btn-sm">
                            <i class="fas fa-arrow-left me-1"></i> Back to Courses
                        </a>
                    }
                    @if (role == "Student")
                    {
                        <a asp-controller="Instructors" asp-action="Home" class="btn btn-outline-primary btn-sm">
                            <i class="fas fa-arrow-left me-1"></i> Back to Courses
                        </a>
                    }
                </div>

                @if (Model.Contents != null && Model.Contents.Any())
                {
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="table-light">
                                <tr>
                                    <th>Title</th>
                                    <th>Date Added</th>
                                    <th>Type</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var content in Model.Contents)
                                {
                                    <tr>
                                        <td class="fw-bold">@content.Title</td>
                                        <td>@content.DateAdded.ToShortDateString()</td>
                                        <td>
                                            <span class="badge bg-@GetContentTypeBadgeClass(content.Type)">
                                                @content.Type
                                            </span>
                                        </td>
                                        <td>
                                            <div class="d-flex">
                                                @if (content.pdfFile != null && content.pdfFile.Length > 0)
                                                {
                                                    <a asp-action="Download" asp-controller="Contents" asp-route-id="@content.ContentId"
                                                       class="btn btn-sm btn-success me-2">
                                                        <i class="fas fa-file-pdf me-1"></i> PDF
                                                    </a>
                                                }
                                                @if (role == "Instructor")
                                                {
                                                    <a asp-action="Edit" asp-controller="Contents" asp-route-id="@content.ContentId"
                                                       class="btn btn-sm btn-outline-warning me-2">
                                                        <i class="fas fa-edit me-1"></i> Edit
                                                    </a>
                                                    <a asp-action="Delete" asp-controller="Contents" asp-route-id="@content.ContentId"
                                                       class="btn btn-sm btn-outline-danger">
                                                        <i class="fas fa-trash me-1"></i> Delete
                                                    </a>
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    <!-- Video Section -->
                    <div class="mt-5">
                        <h5 class="fw-bold gradient-text mb-3">Course Video</h5>
                        <div class="ratio ratio-16x9 rounded-lg overflow-hidden shadow-sm">
                            <iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ?si=y4Xbnr_2N05VpYJ3"
                                    title="YouTube video player"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen>
                            </iframe>
                        </div>
                    </div>
                }
                else
                {
                    <div class="alert alert-info">
                        <i class="fas fa-info-circle me-2"></i> No content available for this course yet.
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<style>
    .gradient-text {
        background: linear-gradient(45deg, var(--primary-color), var(--accent-color));
        -webkit-background-clip: text;
        background-clip: text;
        color: transparent;
    }

    .bg-primary-gradient {
        background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
    }

    .card {
        border-radius: 1rem;
    }

    .table {
        margin-bottom: 0;
    }

        .table th {
            border-top: none;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.75rem;
            letter-spacing: 0.5px;
        }

    .table-hover tbody tr:hover {
        background-color: rgba(67, 97, 238, 0.05);
    }

    .badge {
        font-weight: 500;
        padding: 0.35em 0.65em;
    }

    .ratio-16x9 {
        max-width: 800px;
        margin: 0 auto;
    }
</style>

@functions {
    string GetDifficultyBadgeClass(string difficulty)
    {
        return difficulty switch
        {
            "Beginner" => "success",
            "Intermediate" => "warning",
            "Advanced" => "danger",
            _ => "secondary"
        };
    }

    string GetContentTypeBadgeClass(string type)
    {
        return type switch
        {
            "Lecture" => "info",
            "Reading" => "primary",
            "Exercise" => "success",
            "Video" => "danger",
            _ => "secondary"
        };
    }
}

Views/Courses/Index.cshtml
@model MvcE_Learning.Models.CourseViewModel

@{
    ViewData["Title"] = "Browse Courses";
    var role = Context.Request.Cookies["Role"];
    var name = Context.Request.Cookies["Name"];
    var id = Context.Request.Cookies["Id"];
}

<div class="container py-5">
    <div class="row mb-4">
        <div class="col-12">
            <h1 class="display-5 fw-bold gradient-text mb-4">Browse Our Courses</h1>
            <p class="lead text-muted">Discover the perfect learning path for your goals</p>
        </div>
    </div>

    <div class="card shadow-sm mb-5">
        <div class="card-body p-4">
            <form asp-controller="Courses" asp-action="Index" method="get" class="row g-3 align-items-end">
                <div class="col-md-4">
                    <label class="form-label fw-bold">Filter by Field</label>
                    <select asp-for="CourseFields" asp-items="Model.Fields" class="form-select">
                        <option value="">All Fields</option>
                    </select>
                </div>
                <div class="col-md-5">
                    <label class="form-label fw-bold">Search Courses</label>
                    <div class="input-group">
                        <span class="input-group-text bg-transparent"><i class="fas fa-search"></i></span>
                        <input type="text" asp-for="SearchString" class="form-control" placeholder="Search by course name...">
                    </div>
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-primary w-100">
                        <i class="fas fa-filter me-2"></i> Apply Filters
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
        @foreach (var item in Model.Course!)
        {
            <div class="col">
                <div class="card h-100 border-0 shadow-sm course-card animate__animated animate__fadeIn">
                    <div class="card-header bg-primary bg-opacity-10 py-3">
                        <h5 class="card-title mb-0 fw-bold">@Html.DisplayFor(modelItem => item.Name)</h5>
                    </div>
                    <div class="card-body">
                        <p class="card-text text-muted mb-3">@Html.DisplayFor(modelItem => item.Description)</p>

                        <div class="d-flex flex-wrap gap-2 mb-3">
                            <span class="badge bg-primary bg-opacity-10 text-primary">
                                <i class="fas fa-clock me-1"></i> @Html.DisplayFor(modelItem => item.Duration)
                            </span>
                            <span class="badge bg-warning bg-opacity-10 text-warning">
                                <i class="fas fa-signal me-1"></i> @Html.DisplayFor(modelItem => item.Difficulty)
                            </span>
                            <span class="badge bg-info bg-opacity-10 text-info">
                                <i class="fas fa-tag me-1"></i> @Html.DisplayFor(modelItem => item.Fields)
                            </span>
                        </div>

                        <div class="d-flex align-items-center mb-3">
                            <div class="rating-stars me-2">
                                @for (int i = 0; i < 5; i++)
                                {
                                    if (i < Math.Floor(item.Rating))
                                    {
                                        <i class="fas fa-star text-warning"></i>
                                    }
                                    else if (i < item.Rating)
                                    {
                                        <i class="fas fa-star-half-alt text-warning"></i>
                                    }
                                    else
                                    {
                                        <i class="far fa-star text-warning"></i>
                                    }
                                }
                            </div>
                            <small class="text-muted">@item.Rating.ToString("0.0")</small>
                        </div>
                    </div>
                    <div class="card-footer bg-transparent border-0 pt-0 pb-3">
                        @if (role == "Student")
                        {
                            <a asp-controller="Students" asp-action="Enroll" asp-route-id="@item.CourseId"
                               class="btn btn-primary w-100">
                                <i class="fas fa-book-open me-2"></i> Enroll Now
                            </a>
                        }
                        else if (string.IsNullOrEmpty(role))
                        {
                            <a asp-controller="Home" asp-action="LoginPageOption"
                               class="btn btn-outline-primary w-100">
                                <i class="fas fa-sign-in-alt me-2"></i> Login to Enroll
                            </a>
                        }
                    </div>
                </div>
            </div>
        }
    </div>

    @if (!Model.Course.Any())
    {
        <div class="text-center py-5">
            <img src="https://cdn-icons-png.flaticon.com/512/4076/4076478.png" width="120" class="mb-4 opacity-50">
            <h4 class="fw-bold">No courses found</h4>
            <p class="text-muted">Try adjusting your search filters</p>
            <a asp-controller="Courses" asp-action="Index" class="btn btn-primary mt-3">
                <i class="fas fa-undo me-2"></i> Reset Filters
            </a>
        </div>
    }
</div>

<style>
    .course-card {
        transition: all 0.3s ease;
        border-radius: 0.75rem;
        overflow: hidden;
    }

        .course-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
        }

    .rating-stars {
        font-size: 0.9rem;
    }

    .badge {
        border-radius: 0.5rem;
        padding: 0.35rem 0.65rem;
        font-weight: 500;
    }

    .card-header {
        border-bottom: none;
    }

    .form-select, .form-control {
        border-radius: 0.5rem;
        padding: 0.5rem 1rem;
        border: 1px solid #dee2e6;
    }

        .form-select:focus, .form-control:focus {
            border-color: var(--primary-color);
            box-shadow: 0 0 0 0.25rem rgba(67, 97, 238, 0.25);
        }
</style>

@section Scripts {
    <script>
        // Add animation to course cards as they come into view
        document.addEventListener('DOMContentLoaded', function () {
            const animateCards = function () {
                const cards = document.querySelectorAll('.course-card');
                cards.forEach((card, index) => {
                    const cardPosition = card.getBoundingClientRect().top;
                    const screenPosition = window.innerHeight / 1.3;

                    if (cardPosition < screenPosition) {
                        card.style.animationDelay = `${index * 0.1}s`;
                        card.classList.add('animate__fadeInUp');
                    }
                });
            };

            window.addEventListener('scroll', animateCards);
            animateCards(); // Run once on page load
        });
    </script>
}