Models/Instructor.cs
namespace MvcE_Learning.Models
{
    public class Instructor
    {
        public int InstructorId { get; set; }
        public string Name { get; set;}

        public string Email { get; set;}
        public string Password { get; set;}

        public string FieldOfWork { get; set;}

        public int YearsOfExperience { get; set;}
    }
}

Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcE_Learning.Data;
using MvcE_Learning.Models;

namespace MvcE_Learning.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CourseDbContext _context;
        private readonly InstructorsDbContext _instructorContext;
        private readonly TeachDbContext _teachContext;
        private readonly ContentDbContext _contentContext;

        public CoursesController(CourseDbContext context, InstructorsDbContext instructorContext, TeachDbContext teachContext, ContentDbContext contentContext)
        {
            _context = context;
            _instructorContext = instructorContext;
            _teachContext = teachContext;
            _contentContext = contentContext;
        }

        // GET: Courses
        public async Task<IActionResult> Index(string courseFields, string searchString)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'MvcE_Learning.Course'  is null.");
            }

            
            IQueryable<string> fieldsQuery = from m in _context.Course
                                            orderby m.Fields
                                            select m.Fields;
            var courses = from c in _context.Course
                         select c;

            if (!string.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(s => s.Name!.ToUpper().Contains(searchString.ToUpper()));
            }

            if (!string.IsNullOrEmpty(courseFields))
            {
                courses = courses.Where(x => x.Fields == courseFields);
            }

            var courseFieldVM = new CourseViewModel
            {
                Fields = new SelectList(await fieldsQuery.Distinct().ToListAsync()),
                Course = await courses.ToListAsync()
            };

            return View(courseFieldVM);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courses = from c in _context.Course
                          select c;

            courses = courses.Where(c => c.CourseId == id);

            var course =  courses.FirstOrDefault();

            var content = from c in _contentContext.Content
                          where c.CourseId == id
                          select c;

            ICollection<Content> contents = content.ToList();

            CourseContentViewModel courseContentViewModel = new CourseContentViewModel();

            courseContentViewModel.Course = course;
            courseContentViewModel.Contents = contents;


            if (course == null)
            {
                return NotFound();
            }

            return View(courseContentViewModel);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("courseId,Name,Description,Duration,Difficulty,Fields,Rating")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                var courses = from c in _context.Course
                              select c;

                courses = courses.Where(i => i.Name == course.Name);
                courses = courses.Where(i => i.Description == course.Description);
                var courseId = courses.FirstOrDefault().CourseId;
                Teach teach = new Teach();
                teach.CourseId = courseId;
                teach.InstructorId = Int32.Parse(Request.Cookies["Id"]);
                _teachContext.Add(teach);

                await _teachContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("courseId,Name,Description,Duration,Difficulty,Fields,Rating")] Course course)
        {
            if (id != course.CourseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Course.Any(e => e.CourseId == id);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcE_Learning.Models;
using System.Diagnostics;

namespace MvcE_Learning.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult LoginPageOption()
        {
            return View();
        }

        public IActionResult RedirectInstructor()
        {
            return Redirect("/Instructors/Login");
        }

        public IActionResult RedirectStudent()
        {
            return Redirect("/Students/Login");
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcE_Learning.Data;
using MvcE_Learning.Models;
using System.Net;

namespace MvcE_Learning.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly InstructorsDbContext _context;
        private readonly CourseDbContext _courseContext;
        private readonly TeachDbContext _teachContext;

        public InstructorsController(InstructorsDbContext context, CourseDbContext courseContext, TeachDbContext teachContext)
        {
            _context = context;
            _courseContext = courseContext;
            _teachContext = teachContext;
        }

        // GET: Instructors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Instructors.ToListAsync());
        }

        // GET: Instructors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors
                .FirstOrDefaultAsync(m => m.InstructorId == id);
            if (instructor == null)
            {
                return NotFound();
            }

            return View(instructor);
        }


        // GET: Instructors/Home
        public async Task<IActionResult> Home()
        {
            var courses = from c in _courseContext.Course
                          select c;
            var teaches = from t in _teachContext.Teach
                          select t;
            teaches = teaches.Where(t => t.InstructorId == Int32.Parse(Request.Cookies["Id"]));
            Console.WriteLine("Hello Hello");
            int[] courseIdList = new int[teaches.Count()];
            int counter = 0;
            foreach(Teach t in teaches)
            {
                courseIdList[counter] = t.CourseId;
                counter++;
            }

            courses = courses.Where(c => courseIdList.Contains(c.CourseId));

            Console.WriteLine("Courses is: " + courses.GetType().Name);

            var coursesEnumerable = courses.AsEnumerable();
            return View(coursesEnumerable);
        }

        // GET: Instructors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Instructors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InstructorId,Name,Email,Password,FieldOfWork,YearsOfExperience")] Instructor instructor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(instructor);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
                
            }
            return View(instructor);
        }

        // POST: Instructors/Create
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([Bind("Email,Password")] Instructor instructor)
        {
            if (string.IsNullOrEmpty(instructor.Email) && string.IsNullOrEmpty(instructor.Password))
            {
                return BadRequest();
            }
            var instructorSearch = from i in _context.Instructors
                                   select i;
            instructorSearch = instructorSearch.Where(s =>  s.Email == instructor.Email);
            instructorSearch = instructorSearch.Where(s =>s.Password == instructor.Password);

            Instructor returnInstructor = instructorSearch.FirstOrDefault();

            if(returnInstructor != null)
            {
                Console.WriteLine(returnInstructor.Email);
                HttpContext.Response.Cookies.Append("Role", "Instructor");
                HttpContext.Response.Cookies.Append("Name", returnInstructor.Name);
                HttpContext.Response.Cookies.Append("Id", returnInstructor.InstructorId.ToString());
                return Redirect("/Instructors/Home");

            }
            else
            {
                InstructorLoginSuccess instructorLoginSuccess = new InstructorLoginSuccess();
                instructorLoginSuccess.success = false;
                return View(instructorLoginSuccess);

            }

            
        }

        // POST: Instructors/LogOut
        public IActionResult LogOut()
        {
            HttpContext.Response.Cookies.Delete("Role");
            HttpContext.Response.Cookies.Delete("Registered");
            HttpContext.Response.Cookies.Delete("Name");
            return Redirect("/");
        }

        // GET: Instructors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors.FindAsync(id);
            if (instructor == null)
            {
                return NotFound();
            }
            return View(instructor);
        }

        // POST: Instructors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InstructorId,Name,Email,Password,FieldOfWork,YearsOfExperience")] Instructor instructor)
        {
            if (id != instructor.InstructorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(instructor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstructorExists(instructor.InstructorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(instructor);
        }

        // GET: Instructors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructor = await _context.Instructors
                .FirstOrDefaultAsync(m => m.InstructorId == id);
            if (instructor == null)
            {
                return NotFound();
            }

            return View(instructor);
        }

        // POST: Instructors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var instructor = await _context.Instructors.FindAsync(id);
            if (instructor != null)
            {
                _context.Instructors.Remove(instructor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InstructorExists(int id)
        {
            return _context.Instructors.Any(e => e.InstructorId == id);
        }
    }
}

Views/Instructors/Details.cshtml
@model MvcE_Learning.Models.Instructor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FieldOfWork)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FieldOfWork)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.YearsOfExperience)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.YearsOfExperience)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.InstructorId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Instructors/Edit.cshtml
@model MvcE_Learning.Models.Instructor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Instructor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InstructorId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FieldOfWork" class="control-label"></label>
                <input asp-for="FieldOfWork" class="form-control" />
                <span asp-validation-for="FieldOfWork" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearsOfExperience" class="control-label"></label>
                <input asp-for="YearsOfExperience" class="form-control" />
                <span asp-validation-for="YearsOfExperience" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Instructors/Home.cshtml
@model IEnumerable<MvcE_Learning.Models.Course>

@{
    ViewData["Title"] = "Instructor Home";
}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="card shadow-lg border-0 rounded-lg overflow-hidden">
                <div class="card-header bg-primary-gradient text-white py-3">
                    <div class="d-flex justify-content-between align-items-center">
                        <h2 class="h3 mb-0 fw-bold gradient-text">
                            <i class="fas fa-chalkboard-teacher me-2"></i> Your Courses
                        </h2>
                        <a class="btn btn-light btn-sm" asp-controller="Courses" asp-action="Create">
                            <i class="fas fa-plus me-1"></i> Create New Course
                        </a>
                    </div>
                </div>

                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-hover align-middle mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th class="ps-4">@Html.DisplayNameFor(model => model.Name)</th>
                                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                                    <th>@Html.DisplayNameFor(model => model.Duration)</th>
                                    <th>@Html.DisplayNameFor(model => model.Difficulty)</th>
                                    <th>@Html.DisplayNameFor(model => model.Fields)</th>
                                    <th>@Html.DisplayNameFor(model => model.Rating)</th>
                                    <th class="text-end pe-4">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model!)
                                {
                                    <tr>
                                        <td class="ps-4 fw-semibold">@Html.DisplayFor(modelItem => item.Name)</td>
                                        <td class="text-truncate" style="max-width: 200px;">@Html.DisplayFor(modelItem => item.Description)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Duration)</td>
                                        <td>
                                            <span class="badge bg-@(item.Difficulty == "Beginner" ? "success" : item.Difficulty == "Intermediate" ? "warning" : "danger")">
                                                @Html.DisplayFor(modelItem => item.Difficulty)
                                            </span>
                                        </td>
                                        <td>@Html.DisplayFor(modelItem => item.Fields)</td>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <span class="text-warning me-1">
                                                    @for (int i = 0; i < Math.Floor(item.Rating); i++)
                                                    {
                                                        <i class="fas fa-star"></i>
                                                    }
                                                    @if (item.Rating % 1 > 0)
                                                    {
                                                        <i class="fas fa-star-half-alt"></i>
                                                    }
                                                </span>
                                                <span>@Html.DisplayFor(modelItem => item.Rating)</span>
                                            </div>
                                        </td>
                                        <td class="text-end pe-4">
                                            <div class="btn-group" role="group">
                                                <a class="btn btn-sm btn-outline-primary" asp-controller="Courses" asp-action="Edit" asp-route-id="@item.CourseId">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <a class="btn btn-sm btn-outline-secondary" asp-controller="Courses" asp-action="Details" asp-route-id="@item.CourseId">
                                                    <i class="fas fa-info-circle"></i>
                                                </a>
                                                <a class="btn btn-sm btn-outline-danger" asp-controller="Courses" asp-action="Delete" asp-route-id="@item.CourseId">
                                                    <i class="fas fa-trash-alt"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .bg-primary-gradient {
        background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
    }

    .gradient-text {
        background: linear-gradient(45deg, var(--primary-color), var(--accent-color));
        -webkit-background-clip: text;
        background-clip: text;
        color: transparent;
    }

    .card {
        border-radius: 1rem;
        overflow: hidden;
    }

    .table-hover tbody tr:hover {
        background-color: rgba(67, 97, 238, 0.05);
    }

    .table th {
        border-top: none;
        font-weight: 600;
        text-transform: uppercase;
        font-size: 0.75rem;
        letter-spacing: 0.5px;
        color: #6c757d;
    }

    .badge {
        font-size: 0.75rem;
        font-weight: 500;
        padding: 0.35em 0.65em;
    }
</style>

Views/Instructors/LogOut.cshtml
namespace MvcE_Learning.Views.Instructors
{
    public class LogOut
    {
    }
}

Views/Instructors/Login.cshtml
@model MvcE_Learning.Models.InstructorLoginSuccess

@{
    ViewData["Title"] = "Instructor Login";
    var success = true;
    if (Model != null)
    {
        success = Model.success;
    }
    var id = Context.Request.Cookies["Name"];
}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card shadow-lg border-0 rounded-lg overflow-hidden">
                <div class="row g-0">
                    <!-- Left Side - Illustration -->
                    <div class="col-md-6 d-none d-md-flex bg-primary-gradient align-items-center justify-content-center p-5">
                        <div class="text-center text-white">
                            <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" width="150" class="mb-4">
                            <h3 class="fw-bold mb-3">Welcome Back, Instructor!</h3>
                            <p class="mb-0">Access your teaching dashboard and manage your courses</p>
                        </div>
                    </div>

                    <!-- Right Side - Login Form -->
                    <div class="col-md-6 p-5">
                        <div class="text-center mb-4">
                            <h1 class="h3 fw-bold gradient-text">Instructor Login</h1>
                            <p class="text-muted">Sign in to manage your courses and content</p>
                        </div>

                        @if (success == false)
                        {
                            <div class="alert alert-danger d-flex align-items-center" role="alert">
                                <i class="fas fa-exclamation-circle me-2"></i>
                                Invalid Email or Password. Please try again.
                            </div>
                        }

                        <a class="btn btn-outline-primary w-100 mb-4" asp-area="" asp-controller="Instructors" asp-action="Create">
                            <i class="fas fa-chalkboard-teacher me-2"></i> Don't have an account? Sign up now!
                        </a>

                        <form asp-action="Login" class="needs-validation" novalidate>
                            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

                            <div class="form-floating mb-3">
                                <input type="email" asp-for="instructor.Email" class="form-control" id="emailInput" placeholder=" " required>
                                <label for="emailInput" asp-for="instructor.Email">Email address</label>
                                <span asp-validation-for="instructor.Email" class="text-danger small"></span>
                            </div>

                            <div class="form-floating mb-4">
                                <input type="password" asp-for="instructor.Password" class="form-control" id="passwordInput" placeholder=" " required>
                                <label for="passwordInput" asp-for="instructor.Password">Password</label>
                                <span asp-validation-for="instructor.Password" class="text-danger small"></span>
                            </div>

                            <div class="d-grid mb-3">
                                <button type="submit" class="btn btn-primary btn-lg">
                                    <i class="fas fa-sign-in-alt me-2"></i> Login
                                </button>
                            </div>

                            <div class="text-center">
                                <a href="#" class="text-decoration-none small">Forgot password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .bg-primary-gradient {
        background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
    }

    .gradient-text {
        background: linear-gradient(45deg, var(--primary-color), var(--accent-color));
        -webkit-background-clip: text;
        background-clip: text;
        color: transparent;
    }

    .card {
        border-radius: 1rem;
        overflow: hidden;
    }

    .form-floating label {
        color: #6c757d;
    }

    .form-control {
        padding: 1rem 0.75rem;
        border-radius: 0.5rem;
    }

        .form-control:focus {
            border-color: var(--primary-color);
            box-shadow: 0 0 0 0.25rem rgba(67, 97, 238, 0.25);
        }

    .btn-outline-primary {
        border-color: var(--primary-color);
        color: var(--primary-color);
    }

        .btn-outline-primary:hover {
            background-color: var(--primary-color);
            color: white;
        }

    .alert {
        border-radius: 0.5rem;
    }
</style>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        // Form validation
        (function () {
            'use strict'

            var forms = document.querySelectorAll('.needs-validation')

            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }

                        form.classList.add('was-validated')
                    }, false)
                })
        })()
    </script>
}